# fly.toml app configuration file
app = 'tmdb-embed-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Montamos el volumen directamente en /app/utils para que coincida con el código de la API
[mounts]
  source = "tmdb_data"
  destination = "/app/utils"

[env]
  # Esta ruta asegura que los cambios realizados en el Panel Web se guarden en el volumen
  CONFIG_PATH = "/app/utils/user-config.json"
  NODE_ENV = "production"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  # Subimos a 512MB para mayor estabilidad con múltiples proveedores
  memory_mb = 512
